-- Seed admin user template
-- ================================================================
-- SECURITY WARNING: Do NOT use default passwords in production!
-- ================================================================
--
-- This template shows the required INSERT statement.
-- Replace PLACEHOLDER_HASH with a securely generated Argon2id hash.
--
-- To generate a secure password hash, run:
--   npx tsx scripts/generate-password-hash.ts <your-secure-password>
--
-- Example (DO NOT USE - generate your own):
--   INSERT INTO shared.users (username, email, password_hash, role, is_active)
--   VALUES (
--       'admin',
--       'admin@yourdomain.com',
--       '<YOUR_ARGON2ID_HASH_HERE>',
--       'admin',
--       true
--   );
--
-- For development, use environment variable ADMIN_PASSWORD_HASH or run:
--   docker compose exec gateway npx tsx /app/scripts/create-admin.ts

-- This file is intentionally a template only.
-- Production deployments MUST use environment-based admin creation.
