# ===========================================
# GridWatch NetEnterprise - Loki Configuration
# ===========================================
# Log aggregation with retention and rotation policies
#
# Retention Policies:
#   - Default retention: 31 days (744h)
#   - Old samples rejected: > 7 days
#   - Compaction runs every 10 minutes
#   - Deleted data purged after 2 hours
#
# Storage:
#   - Chunks: /loki/chunks (filesystem)
#   - Index: /loki/tsdb-index (TSDB)
#   - WAL: /loki/wal (write-ahead log)

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_recv_msg_size: 104857600 # 100MB
  grpc_server_max_send_msg_size: 104857600 # 100MB

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# ===========================================
# Schema Configuration
# ===========================================
# Defines how data is stored and indexed
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h # New index table every 24h

# ===========================================
# Storage Configuration
# ===========================================
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

# ===========================================
# Compactor - Log Rotation & Retention
# ===========================================
# The compactor handles:
#   1. Compacting index files for better query performance
#   2. Deleting old data based on retention policies
#   3. Processing delete requests
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
  # Apply retention to all data, including data that hasn't been compacted
  apply_retention_interval: 1h
  delete_max_interval: 24h

# ===========================================
# Limits Configuration - Retention Policies
# ===========================================
limits_config:
  # Global retention period (31 days)
  retention_period: 744h

  # Stream-specific retention (overrides global)
  # Format: {selector}: retention_period
  retention_stream:
    # Keep gateway/API logs for 14 days
    - selector: '{service="gateway"}'
      priority: 1
      period: 336h # 14 days

    # Keep authentication logs for 90 days (compliance)
    - selector: '{service="gateway", log_type="auth"}'
      priority: 2
      period: 2160h # 90 days

    # Keep audit logs for 1 year (compliance)
    - selector: '{log_type="audit"}'
      priority: 3
      period: 8760h # 365 days

    # Keep error logs for 60 days
    - selector: '{level="error"}'
      priority: 4
      period: 1440h # 60 days

    # Keep debug logs for only 7 days
    - selector: '{level="debug"}'
      priority: 5
      period: 168h # 7 days

  # Ingestion limits
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 15MB

  # Stream limits
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000
  max_line_size: 256kb
  max_line_size_truncate: true

  # Sample age limits
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  creation_grace_period: 10m

  # Query limits
  max_query_parallelism: 32
  max_query_series: 10000
  max_query_lookback: 744h # Match retention period
  max_entries_limit_per_query: 10000
  max_chunks_per_query: 2000000

  # Split queries for better performance
  split_queries_by_interval: 1h

  # Cardinality limits
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30

# ===========================================
# Query Configuration
# ===========================================
query_range:
  align_queries_with_step: true
  max_retries: 5
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 1h

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

frontend:
  max_outstanding_per_tenant: 2048
  compress_responses: true
  tail_proxy_url: http://localhost:3100

# ===========================================
# Chunk Store Configuration
# ===========================================
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 1h
  write_dedupe_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100
      ttl: 1h
  max_look_back_period: 0s

# ===========================================
# Ingester Configuration
# ===========================================
ingester:
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 1GB
    flush_on_shutdown: true
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_target_size: 1572864 # 1.5MB
  chunk_retain_period: 1m
  chunk_encoding: snappy
  flush_check_period: 5s
  flush_op_timeout: 10m
  max_chunk_age: 2h
  max_returned_stream_errors: 10

# ===========================================
# Ruler Configuration
# ===========================================
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m

# ===========================================
# Table Manager (Legacy - for older data)
# ===========================================
# Handles periodic table management for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h # 31 days

# ===========================================
# Analytics
# ===========================================
analytics:
  reporting_enabled: false
